# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e7f9a94b7d56eb5a18687839cf96222ffc115b9618ca0e21db2e27051f48a047ad805e0d1494a64baa4f9613430f1ea7065381c3c989cc7295f2ef1ebf60358

test:
  secret_key_base: fad322ad4626e8441285d02d31cecec3128ce15e383f62ad540c4596169e1e00e760d5746b778a67cf2857c2c1c5844faab3beacb613f391d7e417671e4498ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
