# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff812cb5921a8c0092e939a9454f0f5c78dd8544d73ef936460aace93fbd6c46709e26b2eed60f9a117078b8fbfcba599cf009161f0de622705a5300c127753

test:
  secret_key_base: ec07e0ea8b27c2b2bc860530cb45b3e55caab80c55fea8c22adef8a3883815003b0ca8f137581a9ad2b097a35f6ca9f9a804c433b80f0a48c367564670b7bf81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
